import koneksi.KONEKSI;
import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author asus
 */
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class tugas extends javax.swing.JFrame {

    String judul[]=
    {"ID PELANGGAN","NAMA PELANGGAN","ALAMAT","TELEPON","EMAIL"};
    DefaultTableModel FORM_MHS=
    new DefaultTableModel(null,judul);
    private Object J0ptionPane;
    private Object stat;
     
    public tugas() {
        initComponents();
        TampilData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField6 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        IDPL = new javax.swing.JTextField();
        NMPL = new javax.swing.JTextField();
        TLP = new javax.swing.JTextField();
        EM = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        TB = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        AL = new javax.swing.JTextArea();
        SIMPAN = new javax.swing.JButton();
        HAPUS = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jTextField6.setText("jTextField6");

        jTextField10.setBackground(new java.awt.Color(0, 255, 0));
        jTextField10.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jTextField10.setText("EDIT");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setBackground(new java.awt.Color(0, 0, 204));
        jLabel2.setFont(new java.awt.Font("Algerian", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("WAROENG BANDOENG");

        jLabel3.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("ID PELANGGAN  :");

        jLabel4.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setText("NM PELANGGAN:");

        jLabel5.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("ALAMAT              :");

        jLabel6.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel6.setText("TELEPON            :");

        jLabel7.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 204));
        jLabel7.setText(" EMAIL                 :");

        IDPL.setBackground(new java.awt.Color(255, 255, 0));

        NMPL.setBackground(new java.awt.Color(255, 255, 0));

        TLP.setBackground(new java.awt.Color(255, 255, 0));

        EM.setBackground(new java.awt.Color(255, 255, 0));

        TB.setBackground(new java.awt.Color(255, 0, 0));
        TB.setForeground(new java.awt.Color(255, 255, 0));
        TB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID PELANGGAN", "NM PELANGGAN", "ALAMAT", "TELEPON", "EMAIL"
            }
        ));
        TB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TB);

        AL.setBackground(new java.awt.Color(255, 255, 0));
        AL.setColumns(20);
        AL.setRows(5);
        jScrollPane4.setViewportView(AL);

        SIMPAN.setBackground(new java.awt.Color(0, 204, 0));
        SIMPAN.setText("SIMPAN");
        SIMPAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SIMPANActionPerformed(evt);
            }
        });

        HAPUS.setBackground(new java.awt.Color(0, 255, 0));
        HAPUS.setText("HAPUS");
        HAPUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HAPUSActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 255, 0));
        jButton1.setText("BERSIH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(SIMPAN)
                                .addGap(51, 51, 51)
                                .addComponent(HAPUS)))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(EM, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NMPL, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IDPL, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TLP, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IDPL, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NMPL, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(65, 65, 65)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(TLP, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(EM, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SIMPAN, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HAPUS, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBMouseClicked
        // TODO add your handling code here:
                int baris =TB.getSelectedRow();
        if (baris != -1) {
            IDPL.setText(TB.getValueAt(baris, 0).toString());
            NMPL.setText(TB.getValueAt(baris, 1).toString());
            TLP.setText(TB.getValueAt(baris, 2).toString());
            AL.setText(TB.getValueAt(baris, 3).toString());
            NMPL.setText(TB.getValueAt(baris, 4).toString());
        }
    }//GEN-LAST:event_TBMouseClicked

    private void SIMPANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SIMPANActionPerformed
        // TODO add your handling code here:
          String idpl=IDPL.getText();
          String nmpl=NMPL.getText();
          String alamat=AL.getText();
          String telepon=TLP.getText();
          String email =EM.getText();
          
          String idpl1=IDPL.getText();
          String nmpl1=NMPL.getText();
          String alamat1=AL.getText();
          String telepon1=TLP.getText();
          String email1 =EM.getText();
          
        String satu[]=
        {IDPL.getText(),NMPL.getText(),TLP.getText(),AL.getText(),EM.getText()};
        FORM_MHS.addRow(satu);
        if(IDPL.getText().trim().equals(" ")){
                    JOptionPane.showMessageDialog(null,"Masukan Data Untuk Di Input",
                    "PERHATIAN",JOptionPane.WARNING_MESSAGE);}
        else{
                try{
            java.sql.Statement stat=KONEKSI.GetConnection().createStatement();
            ResultSet data=stat.executeQuery
            ("SELECT * FROM pelanggan WHERE id_pelanggan='"+IDPL.getText() + "'");
            if(data.next()) {
                JOptionPane.showMessageDialog(null, "id_pelanggan SUDAH ADA","PERHATIAN",JOptionPane.WARNING_MESSAGE);
                IDPL.requestFocus();}
            
           else{
                        String sql="INSERT INTO pelanggan VALUES('"+idpl1+"'"
                  +",'" +nmpl1+"'"
                  +",'" +alamat1+"'"
                  +",'" +telepon1+"'"
                  +",'" +email1+"')";
                        stat.executeUpdate(sql);
                        IDPL.setText(" ");
                        NMPL.setText(" ");
                        AL.setText(" ");
                        TLP.setText(" ");
                        EM.setText(" ");
                        IDPL.requestFocus();
                        JOptionPane.showMessageDialog(null, "Data berhasil di simpan","Sukses",
                        JOptionPane.INFORMATION_MESSAGE);
                        TampilData();
                }
                
           stat.close();
                }    
           catch (Exception ext) {
        System.out.println("Terjadi Kesalahan : " + ext);
          }
       }
    }//GEN-LAST:event_SIMPANActionPerformed

    private void HAPUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HAPUSActionPerformed
        // TODO add your handling code here:
                            int ok=JOptionPane.showConfirmDialog(null,"Jangan Di Hapus Ath Capee Aku Teh..",
                    "Konfirmasi",JOptionPane.YES_NO_OPTION);
            if(ok==0){
                String sql="DELETE FROM pelanggan WHERE id_pelanggan='"+ IDPL.getText().trim()+ "'";
                try{
            java.sql.Statement stat=KONEKSI.GetConnection().createStatement();
            stat.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Data berhasil di Hapus","Hapus Data"
                    + "",JOptionPane.INFORMATION_MESSAGE);
            stat.close();
                IDPL.setText(" ");
                NMPL.setText(" ");
                AL.setText(" ");
                TLP.setText(" ");
                EM.setText(" ");
                IDPL.requestFocus();
                TampilData();
                }
        catch (Exception ext) {
            System.err.println(sql);
          System.out.println("Error : " + ext);
          }
            }
    }//GEN-LAST:event_HAPUSActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        IDPL.setText("");
        NMPL.setText("");
        AL.setText("");
        TLP.setText("");
        EM.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tugas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AL;
    private javax.swing.JTextField EM;
    private javax.swing.JButton HAPUS;
    private javax.swing.JTextField IDPL;
    private javax.swing.JTextField NMPL;
    private javax.swing.JButton SIMPAN;
    private javax.swing.JTable TB;
    private javax.swing.JTextField TLP;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables

    private void TampilData() {
        DefaultTableModel model= new DefaultTableModel();
        model.addColumn("ID PELANGGAN");
        model.addColumn("NM PELANGGAN");
        model.addColumn("ALAMAT");
        model.addColumn("TELEPON");
        model.addColumn("EMAIL");
        TB.setModel(model);
        try{
            java.sql.Statement stat=KONEKSI.GetConnection().createStatement();
            ResultSet data =stat.executeQuery("SELECT * FROM pelanggan");
            while(data.next()) {
                model.addRow(new Object[] {
                    data.getString("id pelanggan"),
                    data.getString("nm pelanggan"),
                    data.getString("alamat"),
                    data.getString("telepon"),
                    data.getString("email")
                });
                TB.setModel(model);
            }
        }
        catch (Exception e) {
            System.err.println("Terjadi Kesalahan : " + e);
        }
    }
}
