/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author asus
 */
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class Mahasiswa extends javax.swing.JFrame {
    String mhs[]=
    {"NIS","NAMA","ALAMAT","JENIS KELAMIN","AGAMA"};
    DefaultTableModel data_mhs=
            new DefaultTableModel(null,mhs);
    /**
     * Creates new form Mahasiswa
     */
    public Mahasiswa() {
        initComponents();
        tb.setModel(data_mhs);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        nm = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        al = new javax.swing.JLabel();
        nis = new javax.swing.JLabel();
        ns = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        am = new javax.swing.JTextField();
        jk = new javax.swing.JLabel();
        laki = new javax.swing.JRadioButton();
        pr = new javax.swing.JRadioButton();
        agm = new javax.swing.JLabel();
        pl = new javax.swing.JComboBox();
        tmbh = new javax.swing.JButton();
        brsh = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb = new javax.swing.JTable();
        KL = new javax.swing.JButton();
        hps = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nm.setFont(new java.awt.Font("Bernard MT Condensed", 0, 18)); // NOI18N
        nm.setText("NAMA :");
        nm.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel2.setFont(new java.awt.Font("Algerian", 0, 24)); // NOI18N
        jLabel2.setText("Data MAHASISWA");

        al.setFont(new java.awt.Font("Bernard MT Condensed", 0, 18)); // NOI18N
        al.setText("ALAMAT :");
        al.setBorder(new javax.swing.border.MatteBorder(null));

        nis.setFont(new java.awt.Font("Bernard MT Condensed", 0, 18)); // NOI18N
        nis.setText("NIS     :");
        nis.setBorder(new javax.swing.border.MatteBorder(null));

        ns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nsActionPerformed(evt);
            }
        });

        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });

        am.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amActionPerformed(evt);
            }
        });

        jk.setFont(new java.awt.Font("Bernard MT Condensed", 0, 18)); // NOI18N
        jk.setText("JENIS KELAMIN :");
        jk.setBorder(new javax.swing.border.MatteBorder(null));

        buttonGroup1.add(laki);
        laki.setText("LAKI-LAKI");

        buttonGroup1.add(pr);
        pr.setText("PEREMPUAN");

        agm.setFont(new java.awt.Font("Bernard MT Condensed", 0, 18)); // NOI18N
        agm.setText("AGAMA :");
        agm.setBorder(new javax.swing.border.MatteBorder(null));

        pl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pl.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-PILIH-", "ISLAM", "HINDU", "BUDHA", "KRISTEN", "KATOLIK", "NON MUSLIM" }));

        tmbh.setText("TAMBAH.");
        tmbh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmbhActionPerformed(evt);
            }
        });

        brsh.setText("BERSIHKAN.");
        brsh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brshActionPerformed(evt);
            }
        });

        tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NIS", "NAMA", "ALAMAT", "JENIS KELAMIN", "AGAMA"
            }
        ));
        jScrollPane1.setViewportView(tb);

        KL.setText("KELUAR.");
        KL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KLActionPerformed(evt);
            }
        });

        hps.setText("HAPUS.");
        hps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hpsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(al, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                    .addComponent(nm, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                    .addComponent(nis, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ns, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(am, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pr)
                            .addComponent(laki))
                        .addGap(133, 133, 133))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(agm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tmbh)
                .addGap(18, 18, 18)
                .addComponent(brsh)
                .addGap(18, 18, 18)
                .addComponent(KL)
                .addGap(18, 18, 18)
                .addComponent(hps)
                .addGap(37, 37, 37))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nis)
                    .addComponent(ns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jk)
                    .addComponent(laki))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nm)
                            .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(pr)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(al)
                            .addComponent(am, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(agm)
                            .addComponent(pl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tmbh)
                    .addComponent(brsh)
                    .addComponent(KL)
                    .addComponent(hps))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(180, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nsActionPerformed

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void amActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amActionPerformed

    private void tmbhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmbhActionPerformed
        // TODO add your handling code here:
        String jengkel= " ",agama;
        if (laki.isSelected()){
            jengkel="Laki-Laki";
        }
        else {
            jengkel=pr.getText();
        }
        agama=pl.getSelectedItem().toString();
        String satu[]=
        {ns.getText(),nama.getText(),am.getText(),jengkel,agama};
        data_mhs.addRow(satu);
    }//GEN-LAST:event_tmbhActionPerformed

    private void brshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brshActionPerformed
        // TODO add your handling code here:
        ns.setText("");
        nama.setText(" ");
        am.setText(" ");
        laki.setSelected(false);
        pr.setSelected(false);
        pl.setSelectedIndex(-0);
    }//GEN-LAST:event_brshActionPerformed

    private void KLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KLActionPerformed
        // TODO add your handling code here:
        System.exit(0);    
    }//GEN-LAST:event_KLActionPerformed

    private void hpsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hpsActionPerformed
        // TODO add your handling code here:
        DefaultTableModel data_mhs = (DefaultTableModel) tb.getModel();
        int row=tb.getSelectedRow();
        if(row>=0){
            int ok=JOptionPane.showConfirmDialog(null,"Jangan Keluar Dlu Ath Lahhh..",
                    "Kompirmasi",JOptionPane.YES_NO_OPTION);
            if(ok==0){
                data_mhs.removeRow(row);
            }
        }
    }//GEN-LAST:event_hpsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton KL;
    private javax.swing.JLabel agm;
    private javax.swing.JLabel al;
    private javax.swing.JTextField am;
    private javax.swing.JButton brsh;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton hps;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jk;
    private javax.swing.JRadioButton laki;
    private javax.swing.JTextField nama;
    private javax.swing.JLabel nis;
    private javax.swing.JLabel nm;
    private javax.swing.JTextField ns;
    private javax.swing.JComboBox pl;
    private javax.swing.JRadioButton pr;
    private javax.swing.JTable tb;
    private javax.swing.JButton tmbh;
    // End of variables declaration//GEN-END:variables
}
