/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author asus
 */
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class PendaftaranSiswa extends javax.swing.JFrame {
    String judul[]=
    {"No.PENDAFTARAN","JURUSAN","NAMA SISWA","JENIS KELAMIN",
        "TEMPAT LAHIR","TANGGAL LAHIR","AGAMA","ALAMAT LENGKAP","NO TLP","EMAIL"};
    DefaultTableModel PENDAFTARAN_SISWA=
            new DefaultTableModel(null,judul);

    /**
     * Creates new form PendaftaranSiswa
     */
    public PendaftaranSiswa() {
        initComponents();
         tb.setModel(PENDAFTARAN_SISWA);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        nis = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nis1 = new javax.swing.JLabel();
        nis2 = new javax.swing.JLabel();
        nis3 = new javax.swing.JLabel();
        nis4 = new javax.swing.JLabel();
        nis5 = new javax.swing.JLabel();
        nis6 = new javax.swing.JLabel();
        nis7 = new javax.swing.JLabel();
        nis8 = new javax.swing.JLabel();
        nis9 = new javax.swing.JLabel();
        NOP = new javax.swing.JTextField();
        NAMA = new javax.swing.JTextField();
        JURUS = new javax.swing.JComboBox();
        TL = new javax.swing.JTextField();
        TGL = new javax.swing.JTextField();
        NOHP = new javax.swing.JTextField();
        EML = new javax.swing.JTextField();
        laki = new javax.swing.JRadioButton();
        pr = new javax.swing.JRadioButton();
        AGM = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        ARENA = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb = new javax.swing.JTable();
        SIMPAN = new javax.swing.JButton();
        bersih = new javax.swing.JButton();
        KELUAR = new javax.swing.JButton();
        HPS = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 51));

        nis.setFont(new java.awt.Font("Bernard MT Condensed", 0, 18)); // NOI18N
        nis.setText("No.Pendaftaran :");
        nis.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel2.setFont(new java.awt.Font("Algerian", 0, 24)); // NOI18N
        jLabel2.setText("formulir pendaftaran siswa baru");

        nis1.setFont(new java.awt.Font("Bernard MT Condensed", 0, 18)); // NOI18N
        nis1.setText("Jurusan :");
        nis1.setBorder(new javax.swing.border.MatteBorder(null));

        nis2.setFont(new java.awt.Font("Bernard MT Condensed", 0, 18)); // NOI18N
        nis2.setText("Nama Siswa :");
        nis2.setBorder(new javax.swing.border.MatteBorder(null));

        nis3.setFont(new java.awt.Font("Bernard MT Condensed", 0, 18)); // NOI18N
        nis3.setText("Jenis Kelamin :");
        nis3.setBorder(new javax.swing.border.MatteBorder(null));

        nis4.setFont(new java.awt.Font("Bernard MT Condensed", 0, 18)); // NOI18N
        nis4.setText("Tempat Lahir :");
        nis4.setBorder(new javax.swing.border.MatteBorder(null));

        nis5.setFont(new java.awt.Font("Bernard MT Condensed", 0, 18)); // NOI18N
        nis5.setText("Tanggal Lahir :");
        nis5.setBorder(new javax.swing.border.MatteBorder(null));

        nis6.setFont(new java.awt.Font("Bernard MT Condensed", 0, 18)); // NOI18N
        nis6.setText("Agama :");
        nis6.setBorder(new javax.swing.border.MatteBorder(null));

        nis7.setFont(new java.awt.Font("Bernard MT Condensed", 0, 18)); // NOI18N
        nis7.setText("Alamat Lengkap :");
        nis7.setBorder(new javax.swing.border.MatteBorder(null));

        nis8.setFont(new java.awt.Font("Bernard MT Condensed", 0, 18)); // NOI18N
        nis8.setText("No Tlp/Hp :");
        nis8.setBorder(new javax.swing.border.MatteBorder(null));

        nis9.setFont(new java.awt.Font("Bernard MT Condensed", 0, 18)); // NOI18N
        nis9.setText("Email :");
        nis9.setBorder(new javax.swing.border.MatteBorder(null));

        NOP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NOPActionPerformed(evt);
            }
        });

        NAMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NAMAActionPerformed(evt);
            }
        });

        JURUS.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JURUS.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-PILIH JURUSAN-", "RPL", "TKR", "TSM" }));

        TL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TLActionPerformed(evt);
            }
        });

        TGL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TGLActionPerformed(evt);
            }
        });

        NOHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NOHPActionPerformed(evt);
            }
        });

        EML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EMLActionPerformed(evt);
            }
        });

        buttonGroup1.add(laki);
        laki.setText("LAKI-LAKI");

        buttonGroup1.add(pr);
        pr.setText("PEREMPUAN");

        AGM.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AGM.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-PILIH-", "ISLAM", "HINDU", "BUDHA", "KRISTEN", "KATOLIK", "NON MUSLIM" }));

        ARENA.setColumns(20);
        ARENA.setRows(5);
        jScrollPane1.setViewportView(ARENA);

        tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No pendaftaran", "JURUSAN", "NAMA SISWA", "JENIS KELAMIN", "TEMPAT LAHIR", "TANGGAL LAHIR", "AGAMA", "ALAMAT LENGKAP", "NO TLP", "EMAIL"
            }
        ));
        jScrollPane2.setViewportView(tb);

        SIMPAN.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        SIMPAN.setText("simpan.");
        SIMPAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SIMPANActionPerformed(evt);
            }
        });

        bersih.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        bersih.setText("BERSIH.");
        bersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bersihActionPerformed(evt);
            }
        });

        KELUAR.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        KELUAR.setText("KELUAR.");
        KELUAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KELUARActionPerformed(evt);
            }
        });

        HPS.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        HPS.setText("HAPUS.");
        HPS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HPSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nis9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nis8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nis7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nis6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nis5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nis4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nis3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nis2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nis1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nis, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(NOP, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61)
                                .addComponent(SIMPAN)
                                .addGap(36, 36, 36)
                                .addComponent(bersih)
                                .addGap(40, 40, 40)
                                .addComponent(KELUAR)
                                .addGap(34, 34, 34)
                                .addComponent(HPS))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(laki)
                                        .addGap(18, 18, 18)
                                        .addComponent(pr))
                                    .addComponent(JURUS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NAMA, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TL, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TGL, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AGM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NOHP, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EML, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nis)
                    .addComponent(NOP, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SIMPAN)
                    .addComponent(bersih)
                    .addComponent(KELUAR)
                    .addComponent(HPS))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nis1)
                            .addComponent(JURUS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nis2)
                            .addComponent(NAMA, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nis3)
                            .addComponent(laki)
                            .addComponent(pr))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nis4)
                            .addComponent(TL, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nis5)
                            .addComponent(TGL, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nis6)
                            .addComponent(AGM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nis7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nis8))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(NOHP, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nis9)
                            .addComponent(EML, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NOPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NOPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NOPActionPerformed

    private void NAMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NAMAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NAMAActionPerformed

    private void TLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TLActionPerformed

    private void TGLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TGLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TGLActionPerformed

    private void NOHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NOHPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NOHPActionPerformed

    private void EMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EMLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EMLActionPerformed

    private void SIMPANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SIMPANActionPerformed
        // TODO add your handling code here:
        String jengkel= " ",agama,JURUSAN;
        if (laki.isSelected()){
            jengkel="Laki-Laki";
        }
        else {
            jengkel=pr.getText();
        }
        JURUSAN=JURUS.getSelectedItem().toString();
        agama=AGM.getSelectedItem().toString();
        String satu[]=
        {NOP.getText(),JURUSAN,NAMA.getText(),jengkel,TL.getText(),
            TGL.getText(),agama,ARENA.getText(),NOHP.getText(),EML.getText()};
        PENDAFTARAN_SISWA.addRow(satu);
    }//GEN-LAST:event_SIMPANActionPerformed

    private void bersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bersihActionPerformed
        // TODO add your handling code here:
        NOP.setText("");
        JURUS.setSelectedIndex(-0);
        NAMA.setText(" ");
        laki.setSelected(false);
        pr.setSelected(false);
        TL.setText(" ");
        TGL.setText(" ");
        AGM.setSelectedIndex(-0);
        ARENA.setText(" ");
        NOHP.setText(" ");
        EML.setText(" ");
    }//GEN-LAST:event_bersihActionPerformed

    private void KELUARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KELUARActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_KELUARActionPerformed

    private void HPSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HPSActionPerformed
        // TODO add your handling code here:
        DefaultTableModel PENDAFTARAN_SISWA = (DefaultTableModel) tb.getModel();
        int row=tb.getSelectedRow();
        if(row>=0){
            int ok=JOptionPane.showConfirmDialog(null,"Jangan Keluar Dlu Ath Lahhh..",
                    "Kompirmasi",JOptionPane.YES_NO_OPTION);
            if(ok==0){
                PENDAFTARAN_SISWA.removeRow(row);
            }
        }
    }//GEN-LAST:event_HPSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PendaftaranSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PendaftaranSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PendaftaranSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PendaftaranSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PendaftaranSiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox AGM;
    private javax.swing.JTextArea ARENA;
    private javax.swing.JTextField EML;
    private javax.swing.JButton HPS;
    private javax.swing.JComboBox JURUS;
    private javax.swing.JButton KELUAR;
    private javax.swing.JTextField NAMA;
    private javax.swing.JTextField NOHP;
    private javax.swing.JTextField NOP;
    private javax.swing.JButton SIMPAN;
    private javax.swing.JTextField TGL;
    private javax.swing.JTextField TL;
    private javax.swing.JButton bersih;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton laki;
    private javax.swing.JLabel nis;
    private javax.swing.JLabel nis1;
    private javax.swing.JLabel nis2;
    private javax.swing.JLabel nis3;
    private javax.swing.JLabel nis4;
    private javax.swing.JLabel nis5;
    private javax.swing.JLabel nis6;
    private javax.swing.JLabel nis7;
    private javax.swing.JLabel nis8;
    private javax.swing.JLabel nis9;
    private javax.swing.JRadioButton pr;
    private javax.swing.JTable tb;
    // End of variables declaration//GEN-END:variables
}
