import Koneksi.Koneksi2;
import com.mysql.jdbc.Statement;
import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author asus
 */
public class BiodataKaryawan extends javax.swing.JFrame {

    /**
     * Creates new form BiodataKaryawan
     */
    public BiodataKaryawan() {
        initComponents();
         TampilData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        nis = new javax.swing.JLabel();
        nis1 = new javax.swing.JLabel();
        nis2 = new javax.swing.JLabel();
        nis3 = new javax.swing.JLabel();
        nis4 = new javax.swing.JLabel();
        nis5 = new javax.swing.JLabel();
        nim = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        jabatan = new javax.swing.JTextField();
        nohp = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamat = new javax.swing.JTextArea();
        lakilaki = new javax.swing.JRadioButton();
        perempuan = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb = new javax.swing.JTable();
        simpan = new javax.swing.JButton();
        bersih = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        keluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Algerian", 0, 24)); // NOI18N
        jLabel2.setText("biodata karyawan ");

        nis.setFont(new java.awt.Font("Bernard MT Condensed", 0, 18)); // NOI18N
        nis.setText("Id Karyawan :");
        nis.setBorder(new javax.swing.border.MatteBorder(null));

        nis1.setFont(new java.awt.Font("Bernard MT Condensed", 0, 18)); // NOI18N
        nis1.setText("Nama Karyawan :");
        nis1.setBorder(new javax.swing.border.MatteBorder(null));

        nis2.setFont(new java.awt.Font("Bernard MT Condensed", 0, 18)); // NOI18N
        nis2.setText("Jenis Kelamin :");
        nis2.setBorder(new javax.swing.border.MatteBorder(null));

        nis3.setFont(new java.awt.Font("Bernard MT Condensed", 0, 18)); // NOI18N
        nis3.setText("Jabatan :");
        nis3.setBorder(new javax.swing.border.MatteBorder(null));

        nis4.setFont(new java.awt.Font("Bernard MT Condensed", 0, 18)); // NOI18N
        nis4.setText("No Hp :");
        nis4.setBorder(new javax.swing.border.MatteBorder(null));

        nis5.setFont(new java.awt.Font("Bernard MT Condensed", 0, 18)); // NOI18N
        nis5.setText("Alamat :");
        nis5.setBorder(new javax.swing.border.MatteBorder(null));

        nim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nimActionPerformed(evt);
            }
        });

        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });

        jabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jabatanActionPerformed(evt);
            }
        });

        nohp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nohpActionPerformed(evt);
            }
        });

        alamat.setColumns(20);
        alamat.setRows(5);
        jScrollPane1.setViewportView(alamat);

        lakilaki.setText("LAKI-LAKI");

        perempuan.setText("PEREMPUAN");

        tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "idkaryawan", "namakaryawan", "jeniskelamin", "jabatan", "nohp", "alamat"
            }
        ));
        tb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tb);

        simpan.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        simpan.setIcon(new javax.swing.ImageIcon("C:\\POTO\\11-06-33-images.jpg")); // NOI18N
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        bersih.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        bersih.setIcon(new javax.swing.ImageIcon("C:\\POTO\\10-58-09-images.jpg")); // NOI18N
        bersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bersihActionPerformed(evt);
            }
        });

        hapus.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        hapus.setIcon(new javax.swing.ImageIcon("C:\\POTO\\10-56-24-images.jpg")); // NOI18N
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        keluar.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        keluar.setIcon(new javax.swing.ImageIcon("C:\\POTO\\11-05-52-images.jpg")); // NOI18N
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nis4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nis5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nohp)
                            .addComponent(jScrollPane1)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(simpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bersih)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hapus)
                        .addGap(9, 9, 9)
                        .addComponent(keluar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nis1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nis2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nis3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nis, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jabatan)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lakilaki)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(perempuan))
                            .addComponent(nim, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nama, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(98, 98, 98)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(350, 350, 350)
                .addComponent(jLabel2)
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nim, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nis, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nis1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nis2)
                    .addComponent(lakilaki)
                    .addComponent(perempuan))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nis3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(nis4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(nohp, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(nis5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bersih, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(simpan))
                .addGap(175, 175, 175))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nimActionPerformed

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void jabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jabatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jabatanActionPerformed

    private void nohpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nohpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nohpActionPerformed

    private void tbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMouseClicked
        // TODO add your handling code here:
         int baris = tb.getSelectedRow();
        if (baris != -1) {
            nim.setText(tb.getValueAt(baris, 0).toString());
            nama.setText(tb.getValueAt(baris, 1).toString());
            if ("Laki-Laki".equals (tb.getValueAt(baris, 2).toString())){
                lakilaki.setSelected(true);
            }
            else {
                perempuan.setSelected(true);
            }
            jabatan.setText(tb.getValueAt(baris, 3).toString());
            nohp.setText(tb.getValueAt(baris, 4).toString());
            alamat.setText(tb.getValueAt(baris, 5).toString());
        }
    }//GEN-LAST:event_tbMouseClicked

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
                String Nim = nim.getText();
        String Nama = nama.getText();
        String jeniskelamin = null;
        if(lakilaki.isSelected()){
            jeniskelamin="laki-laki";
        }
        else if(perempuan.isSelected()){
            jeniskelamin="perempuan";
        }
        String jabatan1=jabatan.getText();
        String nama1=nama.getText();
        String nim1=nim.getText();
        String nohp1=nohp.getText();
        String alamat1=alamat.getText();
        if(nim.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"mohon masukan data untuk di input",
                "PERHATIAN",JOptionPane.WARNING_MESSAGE);
        }

        else{
            try{
                java.sql.Statement stat =Koneksi2.GetConnection().createStatement();
                ResultSet data= stat.executeQuery("SELECT*FROM biodatakaryawan "
                    + "WHERE IdKaryawan ='"+nim.getText()+"'");
                if(data.next()){
                    JOptionPane.showMessageDialog(null, "nim sudah ada","PERHATIAN",
                        JOptionPane.WARNING_MESSAGE);
                    nim.requestFocus();
                }
                else{
                    String sql="INSERT INTO biodatakaryawan VALUES ('"+nim1+"'"
                    +",'"+nama1+"'"
                    +",'"+jeniskelamin+"'"
                    +",'"+jabatan1+"'"
                    +",'"+nohp1+"'"
                    +",'"+alamat1+"')";        
                    stat.executeUpdate(sql);
                    nim.setText("");
                    nama.setText("");
                    jabatan.setText("");
                    nohp.setText("");
                    alamat.setText("");
                    nim.requestFocus();
                    JOptionPane.showMessageDialog(null, "data berhasil disimpan","SUKSES",
                        JOptionPane.INFORMATION_MESSAGE);
                    TampilData();
                }
                stat.close();
            }catch (Exception exc){
                System.out.println("Terjadi Kesalahan :" + exc);
            }
        }
    }//GEN-LAST:event_simpanActionPerformed

    private void bersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bersihActionPerformed
        // TODO add your handling code here:
        nim.setText("");
        nama.setText("");
        lakilaki.setSelected(false);
        perempuan.setSelected(false);
        jabatan.setText("");
        nohp.setText("");
        alamat. setText("");
    }//GEN-LAST:event_bersihActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
                int ok = JOptionPane.showConfirmDialog(null, "Apakah anda ingin menghapus data ini?",
            "Konfirmasi Dialog",JOptionPane.YES_NO_OPTION);
        if(ok == 0) {
            String sql="DELETE FROM biodatakaryawan WHERE IdKaryawan='"+ nim.getText().trim()+"'";
            try{
                java.sql.Statement stat = Koneksi2.GetConnection().createStatement();
                stat.executeUpdate(sql);
                JOptionPane.showMessageDialog(null,"Data Berhasil di Hapus", "Hapus Data"
                    ,JOptionPane.INFORMATION_MESSAGE);
                stat.close();
                nim.setText("");
                nama.setText("");
                jabatan.setText("");
                nohp.setText("");
                alamat.setText("");
                nim.requestFocus();
                TampilData();
            }
            catch (SQLException exc) {
                System.err.println(sql);
                System.err.println("Error : "+exc);
            }
        }
    }//GEN-LAST:event_hapusActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
        int ok=JOptionPane.showConfirmDialog(null,"yakin mau keluar ?",
        "konfirmasi",JOptionPane.YES_NO_OPTION);
               if(ok==0){

                   this.setVisible(false);
                   new Login1().setVisible(true);
        }
    }//GEN-LAST:event_keluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BiodataKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BiodataKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BiodataKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BiodataKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BiodataKaryawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamat;
    private javax.swing.JButton bersih;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jabatan;
    private javax.swing.JButton keluar;
    private javax.swing.JRadioButton lakilaki;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nim;
    private javax.swing.JLabel nis;
    private javax.swing.JLabel nis1;
    private javax.swing.JLabel nis2;
    private javax.swing.JLabel nis3;
    private javax.swing.JLabel nis4;
    private javax.swing.JLabel nis5;
    private javax.swing.JTextField nohp;
    private javax.swing.JRadioButton perempuan;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tb;
    // End of variables declaration//GEN-END:variables

    private void TampilData() {
         DefaultTableModel model=new DefaultTableModel();
         model.addColumn("idkaryawan");
         model.addColumn("namakaryawan");
         model.addColumn("jeniskelamin");
         model.addColumn("jabatan");
         model.addColumn("nohp");
         model.addColumn("alamat");
         tb.setModel(model);
         //menampilkan data database kedalam tabel
         try{
            java.sql.Statement stat=Koneksi2.GetConnection().createStatement();
            ResultSet data= stat.executeQuery
            ("SELECT * FROM biodatakaryawan");
            while(data.next()){
               model.addRow(new Object[]{
               data.getString("IdKaryawan"),
               data.getString("NamaKaryawan"),
               data.getString("JenisKelamin"),
               data.getString("Jabatan"),
               data.getString("NoHp"),
               data.getString("Alamat")
               });
               tb.setModel(model);
            }
         }
         catch(Exception e){
            System.err.println("terjadi kesalahan" +e );
        }
    }
}
