import Koneksi.koneksi;
import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author asus
 */
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class mahasiswa extends javax.swing.JFrame {
      String judul[]=
    {"NIM","NAMA MAHASISWA","JENIS KELAMIN","JURUSAN","SEMESTER"};
    DefaultTableModel FORM_MHS=
            new DefaultTableModel(null,judul);
    private Object J0ptionPane;
    private Object stat;

    /**
     * Creates new form mahasiswa
     */
    public mahasiswa() {
        initComponents();
         TampilData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nis1 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        nis = new javax.swing.JLabel();
        nis2 = new javax.swing.JLabel();
        nis3 = new javax.swing.JLabel();
        jk = new javax.swing.JLabel();
        agm = new javax.swing.JLabel();
        JURUS = new javax.swing.JComboBox();
        laki = new javax.swing.JRadioButton();
        pr = new javax.swing.JRadioButton();
        NIM = new javax.swing.JTextField();
        NM = new javax.swing.JTextField();
        SMTR = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb = new javax.swing.JTable();
        simpan = new javax.swing.JButton();
        BATAL = new javax.swing.JButton();
        HPS = new javax.swing.JButton();
        KELUAR3 = new javax.swing.JButton();
        KELUAR4 = new javax.swing.JButton();
        KL = new javax.swing.JButton();

        nis1.setFont(new java.awt.Font("Bernard MT Condensed", 0, 18)); // NOI18N
        nis1.setText("NIS     :");
        nis1.setBorder(new javax.swing.border.MatteBorder(null));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Algerian", 0, 24)); // NOI18N
        jLabel2.setText("Data MAHASISWA");

        nis.setFont(new java.awt.Font("Bernard MT Condensed", 0, 18)); // NOI18N
        nis.setText("NIM     :");
        nis.setBorder(new javax.swing.border.MatteBorder(null));

        nis2.setFont(new java.awt.Font("Bernard MT Condensed", 0, 18)); // NOI18N
        nis2.setText("NAMA MAHASISWA :");
        nis2.setBorder(new javax.swing.border.MatteBorder(null));

        nis3.setFont(new java.awt.Font("Bernard MT Condensed", 0, 18)); // NOI18N
        nis3.setText("SEMESTER :");
        nis3.setBorder(new javax.swing.border.MatteBorder(null));

        jk.setFont(new java.awt.Font("Bernard MT Condensed", 0, 18)); // NOI18N
        jk.setText("JENIS KELAMIN :");
        jk.setBorder(new javax.swing.border.MatteBorder(null));

        agm.setFont(new java.awt.Font("Bernard MT Condensed", 0, 18)); // NOI18N
        agm.setText("JURUSAN :");
        agm.setBorder(new javax.swing.border.MatteBorder(null));

        JURUS.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JURUS.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-PILIH JURUSAN-", "RPL", "TKR", "TSM", "LISTRIK", "TJK", " " }));

        buttonGroup1.add(laki);
        laki.setText("LAKI-LAKI");

        buttonGroup1.add(pr);
        pr.setText("PEREMPUAN");

        NIM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NIMActionPerformed(evt);
            }
        });

        NM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NMActionPerformed(evt);
            }
        });

        SMTR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SMTRActionPerformed(evt);
            }
        });

        tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NIM", "NAMA MHS", "JENIS KELAMIN", "JURUSAN", "SEMESTER"
            }
        ));
        tb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb);

        simpan.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        simpan.setText("SIMPAN.");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        BATAL.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        BATAL.setText("BATAL.");
        BATAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BATALActionPerformed(evt);
            }
        });

        HPS.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        HPS.setText("HAPUS.");
        HPS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HPSActionPerformed(evt);
            }
        });

        KELUAR3.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        KELUAR3.setText("CARI.");
        KELUAR3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KELUAR3ActionPerformed(evt);
            }
        });

        KELUAR4.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        KELUAR4.setText("UBAH");
        KELUAR4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KELUAR4ActionPerformed(evt);
            }
        });

        KL.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        KL.setText("KELUAR.");
        KL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(366, 366, 366)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(nis, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(NIM, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jk, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                .addComponent(agm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(97, 97, 97)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(laki)
                                    .addGap(30, 30, 30)
                                    .addComponent(pr))
                                .addComponent(JURUS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nis2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nis3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(84, 84, 84)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(SMTR)
                                .addComponent(NM, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(simpan)
                            .addComponent(KELUAR3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BATAL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(KELUAR4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(KL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(HPS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nis)
                            .addComponent(NIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nis2)
                            .addComponent(NM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jk)
                            .addComponent(laki)
                            .addComponent(pr))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(agm)
                            .addComponent(JURUS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nis3)
                            .addComponent(SMTR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(simpan)
                            .addComponent(BATAL)
                            .addComponent(HPS))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(KELUAR3)
                            .addComponent(KELUAR4)
                            .addComponent(KL))))
                .addContainerGap(216, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NIMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NIMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NIMActionPerformed

    private void NMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NMActionPerformed

    private void SMTRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SMTRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SMTRActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
          String nim=NIM.getText();
          String nama=NM.getText();
          String semester=SMTR.getText();
        String jengkel= " ",JURUSAN;
        if (laki.isSelected()){
            jengkel="Laki-Laki";
        }
        else {
            jengkel=pr.getText();
        }
        JURUSAN=JURUS.getSelectedItem().toString();
          
        String satu[]=
        {NIM.getText(),NM.getText(),jengkel,JURUSAN,SMTR.getText()};
        FORM_MHS.addRow(satu);
        if(NIM.getText().trim().equals(" ")){
                    JOptionPane.showMessageDialog(null,"Masukan Data Untuk Di Input",
                    "PERHATIAN",JOptionPane.WARNING_MESSAGE);}
        else{
                try{
            java.sql.Statement stat=koneksi.GetConnection().createStatement();
            ResultSet data=stat.executeQuery
            ("SELECT * FROM loginmahasiswa WHERE NIM='"+NIM.getText() + "'");
            if(data.next()) {
                JOptionPane.showMessageDialog(null, "NIM SUDAH ADA","PERHATIAN",JOptionPane.WARNING_MESSAGE);
                NIM.requestFocus();}
            
           else{
                        String sql="INSERT INTO loginmahasiswa VALUES('"+nim+"'"
                  +",'" +nama+"'"
                  +",'" +jengkel+"'"
                  +",'" +JURUSAN+"'"
                  +",'" +semester+"')";
                        stat.executeUpdate(sql);
                        NIM.setText(" ");
                        NM.setText(" ");
                        JURUS.setSelectedIndex(-0);
                        SMTR.setText(" ");
                        NIM.requestFocus();
                        JOptionPane.showMessageDialog(null, "Data berhasil di simpan","Sukses",
                        JOptionPane.INFORMATION_MESSAGE);
                        TampilData();
                }
                
           stat.close();
                }    
           catch (Exception ext) {
        System.out.println("Terjadi Kesalahan : " + ext);
          }
       }         
    }//GEN-LAST:event_simpanActionPerformed

    private void BATALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BATALActionPerformed
        // TODO add your handling code here:
        NIM.setText("");
        NM.setText("");
        laki.setSelected(false);
        pr.setSelected(false);
        JURUS.setSelectedIndex(-0);
        SMTR.setText("");

    }//GEN-LAST:event_BATALActionPerformed

    private void HPSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HPSActionPerformed

            int ok=JOptionPane.showConfirmDialog(null,"Jangan Di Hapus Ath Capee Aku Teh..",
                    "Konfirmasi",JOptionPane.YES_NO_OPTION);
            if(ok==0){
                String sql="DELETE FROM loginmahasiswa WHERE NIM='"+ NIM.getText().trim()+ "'";
                try{
            java.sql.Statement stat=koneksi.GetConnection().createStatement();
            stat.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Data berhasil di Hapus","Hapus Data"
                    + "",JOptionPane.INFORMATION_MESSAGE);
            stat.close();
                NIM.setText(" ");
                NM.setText(" ");
                JURUS.setSelectedIndex(-0);
                SMTR.setText(" ");
                NIM.requestFocus();
                TampilData();
                }
        catch (Exception ext) {
            System.err.println(sql);
          System.out.println("Error : " + ext);
          }
            }
        
    }//GEN-LAST:event_HPSActionPerformed

    private void KELUAR3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KELUAR3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KELUAR3ActionPerformed

    private void KELUAR4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KELUAR4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KELUAR4ActionPerformed

    private void KLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KLActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_KLActionPerformed

    private void tbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMouseClicked
        // TODO add your handling code here:
        int baris =tb.getSelectedRow();
        if (baris != -1) {
            NIM.setText(tb.getValueAt(baris, 0).toString());
            NM.setText(tb.getValueAt(baris, 1).toString());
            if("laki-laki".equals(tb.getValueAt(baris, 2).toString())) {
                laki.setSelected(true);
            }
            else {
                pr.setSelected(true);
            }
        }
        JURUS.setSelectedItem(tb.getValueAt(baris, 3).toString());
        SMTR.setText(tb.getValueAt(baris, 4).toString());
    }//GEN-LAST:event_tbMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BATAL;
    private javax.swing.JButton HPS;
    private javax.swing.JComboBox JURUS;
    private javax.swing.JButton KELUAR3;
    private javax.swing.JButton KELUAR4;
    private javax.swing.JButton KL;
    private javax.swing.JTextField NIM;
    private javax.swing.JTextField NM;
    private javax.swing.JTextField SMTR;
    private javax.swing.JLabel agm;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jk;
    private javax.swing.JRadioButton laki;
    private javax.swing.JLabel nis;
    private javax.swing.JLabel nis1;
    private javax.swing.JLabel nis2;
    private javax.swing.JLabel nis3;
    private javax.swing.JRadioButton pr;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tb;
    // End of variables declaration//GEN-END:variables

    private void TampilData() {

    }
}
